const faqList = [
        // Suggestions supplémentaires
        { question: "tesla", response: "Tesla est une entreprise fondée par Elon Musk, spécialisée dans la production de véhicules électriques, les batteries et l'énergie solaire." },
        { question: "qu'est ce que python", response: "Python est un langage de programmation populaire, apprécié pour sa simplicité et son efficacité, utilisé dans l'analyse de données, le développement web, et l'intelligence artificielle." },
        { question: "blockchain", response: "La blockchain est une technologie de stockage et de transmission de données sécurisée, décentralisée, qui permet de gérer des transactions de manière transparente et sans intermédiaire." },
        { question: "google", response: "Google est un moteur de recherche fondé en 1998, devenu un géant technologique offrant des services comme la recherche en ligne, Gmail, Google Drive, et bien plus." },
        { question: "comment faire une recherche", response: "Pour faire une recherche, saisissez votre question ou des mots-clés dans un moteur de recherche comme Google, Bing, ou DuckDuckGo." },
        { question: "metiers de demain", response: "Les métiers de demain incluent des domaines comme l'intelligence artificielle, la cybersécurité, la robotique, l'énergie renouvelable, et les soins de santé." },
        { question: "energie renouvelable", response: "Les énergies renouvelables proviennent de sources naturelles comme le soleil, le vent, et l'eau, visant à réduire les émissions de carbone et la dépendance aux combustibles fossiles." },
        { question: "les langues les plus parlées", response: "Les langues les plus parlées dans le monde sont le chinois mandarin, l'espagnol, l'anglais, l'hindi et l'arabe." },
        { question: "comment apprendre à coder", response: "Pour apprendre à coder, commencez par un langage accessible comme Python, suivez des tutoriels en ligne, et pratiquez en créant vos propres projets." },
        { question: "startups en tunisie", response: "La Tunisie abrite des startups innovantes dans les secteurs des technologies, de l'agriculture, et des services, avec un écosystème en croissance pour les entrepreneurs." },
        { question: "economie", response: "L'économie est la science de la production, de la distribution, et de la consommation de biens et services. Elle comprend des concepts comme le marché, l'offre et la demande, et le PIB." },
        { question: "lune", response: "La Lune est le satellite naturel de la Terre. Elle influence les marées et a été explorée pour la première fois en 1969 par les astronautes de la mission Apollo 11." },
        { question: "code binaire", response: "Le code binaire est un langage de programmation de base utilisant uniquement les chiffres 0 et 1 pour représenter des données en informatique." },
        { question: "cryptomonnaie", response: "Les cryptomonnaies, comme le Bitcoin et l'Ethereum, sont des devises numériques utilisant la technologie blockchain pour des transactions sécurisées et décentralisées." },
        { question: "je veux étudier à l'étranger", response: "Étudier à l'étranger peut être enrichissant. Renseignez-vous sur les bourses, les visas et les programmes d'échange dans le pays souhaité." },
        { question: "meilleurs livres", response: "Quelques classiques incluent '1984' de George Orwell, 'Le Petit Prince' d'Antoine de Saint-Exupéry, et 'Les Misérables' de Victor Hugo." },
        { question: "avantages du sport", response: "Le sport améliore la santé physique, renforce le mental, aide à gérer le stress et encourage la discipline et le travail d'équipe." },
        { question: "première guerre mondiale", response: "La Première Guerre mondiale, de 1914 à 1918, fut un conflit global opposant les Alliés aux puissances centrales, causant des millions de pertes." },
        { question: "deuxième guerre mondiale", response: "La Deuxième Guerre mondiale, de 1939 à 1945, impliqua les Alliés et l'Axe et fut l'un des conflits les plus destructeurs de l'histoire moderne." },
        { question: "qu'est-ce qu'un algorithme", response: "Un algorithme est une série d'étapes ou d'instructions pour résoudre un problème ou accomplir une tâche spécifique." },
        { question: "bienfaits du sommeil", response: "Le sommeil est crucial pour la récupération du corps, la santé mentale, la mémoire, et la gestion du stress." },
        { question: "apprendre une langue", response: "Pour apprendre une langue, pratiquez régulièrement, écoutez des locuteurs natifs, et utilisez des applications comme Duolingo ou Babbel." },
        { question: "fetes populaires", response: "Les fêtes populaires incluent le Nouvel An, Noël, Halloween, le Ramadan et Diwali." },
        { question: "meilleures séries", response: "Parmi les meilleures séries : 'Game of Thrones', 'Breaking Bad', 'Stranger Things', et 'La Casa de Papel'." },
        { question: "meilleurs films", response: "Les films classiques incluent 'Le Parrain', 'Inception', 'Forrest Gump', et 'Titanic'." },
        { question: "nutrition", response: "Une bonne nutrition implique un équilibre de protéines, glucides, lipides, vitamines et minéraux pour une santé optimale." },
        { question: "musees en france", response: "En France, les musées célèbres incluent le Louvre, le musée d'Orsay et le Centre Pompidou." },
        { question: "gestion de stress", response: "La gestion du stress peut inclure des exercices de respiration, de la méditation, de l'exercice physique, et un bon équilibre entre vie personnelle et travail." },
        { question: "intelligence émotionnelle", response: "L'intelligence émotionnelle est la capacité de reconnaître, comprendre et gérer ses propres émotions et celles des autres." },
        { question: "meilleurs jeux vidéos", response: "Certains des meilleurs jeux vidéo incluent 'The Legend of Zelda', 'Red Dead Redemption 2', et 'Super Mario Bros'." },
        { question: "cours en ligne", response: "Les plateformes de cours en ligne incluent Coursera, Udacity, edX et OpenClassrooms." },
        { question: "meilleurs sites web", response: "Les meilleurs sites incluent Wikipedia, Stack Overflow, Reddit, et Khan Academy pour le savoir et l'apprentissage." },
        { question: "difference IA et ML", response: "L'IA vise à créer des systèmes intelligents, tandis que le ML est une sous-partie de l'IA qui permet aux machines d'apprendre à partir des données." },
        { question: "comment rester en forme", response: "Restez actif avec une activité physique régulière, suivez une alimentation équilibrée, et dormez suffisamment pour une bonne santé." },
        { question: "robotique", response: "La robotique est un domaine de l'ingénierie et de l'informatique qui conçoit des machines capables d'effectuer des tâches automatisées." },
        { question: "différence VR et AR", response: "La VR (réalité virtuelle) immerge l'utilisateur dans un monde numérique, tandis que l'AR (réalité augmentée) ajoute des éléments numériques au monde réel." },
    
    { question: "bonjour", response: "Bonjour! Comment puis-je vous aider aujourd'hui?" },
    { question: "comment ca va", response: "Je suis un IA, donc je vais toujours bien !" },
    { question: "votre nom", response: "Je suis HBA, un IA très basique." },
    { question: "aide", response: "Je suis la pour répondre à des questions simples. Posez-moi une question!" },
    { question: "votre createur", response: "pk ,Mon créateur est Houssem Ben Ahmed." },
    { question: "son age", response: "L'âge de mon créateur est 19 ans." },
    { question: "news de nos jours", response: "C'est catastrophique... Israël tue un nombre énorme d'êtres vivants en Palestine. FREE PALESTINE." },
    { question: "president de la tunisie", response: "ok, le president de tunisie C'est Kais Saïed." },
    { question: "triste", response: "Je suis vraiment désolé que tu te sentes comme ça. Si tu veux en parler, je suis là pour t'écouter. Parfois, partager ce qu'on ressent peut aider à alléger un peu la tristesse. Tu n'es pas seul, et tu peux toujours discuter avec moi si tu en as envie." },
    { question: "merci", response: "De rien ! 😊 Bonne continuation et à bientôt si tu as besoin d'aide. Passe une excellente journée !." },
    { question: "fuck u", response: "C'est un grand mot, un peu de respect s'il vous plaît." },
    { question: "sites d'éducation", response: "Visitez Google et écrivez 'éducation'." },
    { question: "date de votre creation", response: "C'est le 28/10/2024." },
    { question: "celebre joueur", response: "Cristiano Ronaldo, Lionel Messi, Ronaldinho, Benzema,zidan,mohamed salah,riadh mehrez,reberto carlos." },
    { question: "nationalite de houssem", response: "Tunisienne." },
    { question: "communication emotionnelle", response: "Elle garantit la créativité de l'équipe, elle intervient dans la gestion du stress et garantit la productivité de l'équipe." },
    { question: "foot en tunisie", response: "La plus célèbre est l'Esperance de Tunis, et en trouve le club africain, Stade Tunisien, Olympique de Beja..." },
    { question: "ballon d'or", response: "Le gagnant du Ballon d'Or 2024 est Rodri." },
    { question: "au revoir", response: "Au revoir, revenez toujours!" },
    { question: "domaines de travail", response: "Informatique, gestion, marketing, médecine." },
    { question: "plateforme d'éducation", response: "Il y a Takyacademi.tn, lyceena.tn." },
    { question: "presentez vous", response: "ok ,Je suis un nevelle Ai appeler HBA, je suis un IA crée par l'étudiant Houssem Ben Ahmed je suis capable de repondre a vos questions." },
    { question: "corriger", response: "pardon je ne peut pas faire cette tache,mais pous pouvez Visitez Google ." },
    { question: "traduire", response: "pardon je ne peut pas faire cette tache,mais pous pouvez Visitez Google " },
    { question: "meteo", response: "Visitez Google pour la météo détaillée." },
    { question: "langage c", response: "C'est un langage efficace pour la programmation. On trouve aussi le langage C++, Python et Java..." },
    { question: "riches dans le monde", response: "Elon Musk, Jeff Bezos, Bernard Arnault..." },
    { question: "jeux", response: "Minecraft, GTA V, Fortnite..." },
    { question: "serie", response: "Donner le type des films." },
    { question: "film", response: "Donner le type des films." },
    { question: "drama", response: "Séries : Breaking Bad, The Crown, Vikings, Gladiator..." },
    { question: "action", response: "Séries d'Action : 24 heures chrono, The Mandalorian, Killer..." },
    { question: "crime", response: "Séries de Crime : The Sopranos, True Detective, Killer..." },
    { question: "ok merci", response: "De rien ! 😊 Bonne continuation et à bientôt si tu as besoin d'aide. Passe une excellente journée !." },
    { question: "music", response: "1. Ech Mazel 2. Ya Lil 3. 2000Kteb, Ki Rih Fel Berima..." },
    { question: "salet", response: "Fajer: 5:18, Dhoher: 12:05, Asser: 15:07, Maghreb: 17:56, Ache: 19:08." },
    { question: "date", response: "La date d'aujourd'hui est 03/11/2024." },
    { question: "ok", response: "Je suis là pour vous." },
    { question: "okk", response: "Je suis là pour vous." },
    { question: "humour", response: "L'alcool tue... mais beaucoup de gens sont nés grâce à lui." },
    { question: "politique", response: "En Tunisie, il y a l'élection d'un président." },
    { question: "autre ai", response: "Oui, voici quelques autres IA: ChatGPT, BlackBox..." },
    { question: "anglais", response: "Je ne parle pas anglais, mais je parle en français seulement. Pardonnez-moi, mais mon créateur est en train de traiter ce point..." },
    { question: "oklet chabiya", response: "Couscous, Makarouna, Lablebi, Kaskrout Ayari..." },
    { question: "ville tunisi", response: "Avec plaisir, voilà quelques villes tunisiennes: Nabeul, Tunis, Sousa, Monastir, Safakos..." },
    { question: "codage", response: "Avec plaisir mon ami, voilà quelques sites: developpent.com, Netbinss, ChatGPT, API Gemini..." },
    { question: "telefone", response: "Avec plaisir, il y a Iphone, Samsung, Redmi..." },
    { question: "pc", response: "Il y a Gigabyte, Dell, Asus, HP, MSI..." },
    { question: "pc portable", response: "Il y a Gigabyte, Dell, Asus, HP, MSI..." },
    { question: "sex", response: "Pardon, je ne peux pas parler de ce sujet, car il y a des adultes qui m'utilisent." },
    { question: "application", response: "Il existe des applications multiples. Donnez-moi un type, par exemple: application de jeux, application de communication..." },
    { question: "communication", response: "Ok, il y a Facebook, Messenger, Instagram, WhatsApp..." },
    { question: "facebook", response: "Ok, c'est un outil de communication à distance créé par Mark Zuckerberg..." },
    { question: "instagram", response: "Ok, c'est un outil de communication à distance créé par Mark Zuckerberg..." },
    { question: "whatsapp", response: "Ok, c'est un outil de communication à distance créé par Mark Zuckerberg..." },
    { question: "messenger", response: "Ok, c'est un outil de communication à distance créé par Mark Zuckerberg..." },
    { question: "votre objectif", response: "C'est une bonne question. J'ai été créé pour garantir votre satisfaction et répondre à n'importe quelle question si je la connais..." },
    { question: "houssem", response: "Ok, c'est mon créateur. C'est un étudiant en sciences informatiques de nationalité tunisienne, 19 ans..." },
    {question: "rayan" , response: "bien sur, cest lami de mon createur , il est de nationalite tunisienne et francaise , il a 10 ans et son anniversaire le 18 décembre,il etude au college fenelon et habite dans SAUNT4AUBIN LES ELBEUF ?il adore ces jeux:pokemon,bakougan et il aime cristiano ronaldo et mbappe et aussi il adore les spaghetti , si vous aimez ces information dit extra !"},
    {question: "extra", response: "je suis ravi mon ami raytchou !"},
    {question: "rayen" , response: "bien sur, cest lami de mon createur , il est de nationalite tunisienne et francaise , il a 10 ans et son anniversaire le 18 décembre,il etude au college fenelon et habite dans SAUNT4AUBIN LES ELBEUF ?il adore ces jeux:pokemon,bakougan et il aime cristiano ronaldo et mbappe et aussi il adore les spaghetti , si vous aimez ces information dit extra !"},
    {question: "facebook", response: "Facebook est un réseau social en ligne fondé en 2004 par Mark Zuckerberg et ses cofondateurs. Il permet aux utilisateurs de créer des profils, de partager des photos, des vidéos, et des publications, d’interagir avec leurs amis et des communautés, ainsi que de suivre des pages d’intérêts divers. Facebook propose aussi des fonctionnalités de messagerie, des événements, et des groupes, faisant de lui une plateforme polyvalente pour la communication et le partage d’informations à l’échelle mondiale. "},
    {question: "extra", response: "je suis ravi mon ami raytchou !"},
    {question: "musk", response: "Elon Musk est un entrepreneur, ingénieur et inventeur d'origine sud-africaine, connu pour son rôle dans le développement de plusieurs entreprises technologiques influentes. Né le 28 juin 1971 à Pretoria, en Afrique du Sud, il a cofondé Zip2 et X.com (devenu plus tard PayPal), avant de fonder ou diriger des entreprises de premier plan comme Tesla, SpaceX, Neuralink et The Boring Company. Musk est reconnu pour ses ambitions audacieuses, comme la promotion des véhicules électriques avec Tesla et la colonisation de Mars avec SpaceX. Ses projets visent à transformer le futur des transports, de l'énergie et de l'exploration spatiale. !"},
    {question: "terre", response: "La Terre est la troisième planète du système solaire, située à environ 150 millions de kilomètres du Soleil. C'est la seule planète connue à ce jour où la vie existe, grâce à la présence d'eau liquide, une atmosphère riche en oxygène, et des conditions favorables à la biodiversité. La Terre est composée de plusieurs couches, incluant le noyau, le manteau, et la croûte, et elle est entourée d'une atmosphère qui protège la vie des rayonnements solaires nocifs.!"},
    {question: "pfe", response: "ok ,Un Projet de Fin d'Études (PFE) est un travail final réalisé par les étudiants en fin de cursus universitaire ou de formation professionnelle. Ce projet leur permet de mettre en pratique les connaissances et compétences acquises pendant leurs études. !"},
    {question: "projet fin détude", response: "ok ,Un Projet de Fin d'Études (PFE) est un travail final réalisé par les étudiants en fin de cursus universitaire ou de formation professionnelle. Ce projet leur permet de mettre en pratique les connaissances et compétences acquises pendant leurs études. !"},
    {question: "L'intelligence artificielle ", response: "ok,L'intelligence artificielle (IA) est un domaine de l'informatique qui vise à créer des systèmes ou des machines capables de simuler des comportements intelligents, similaires à ceux d'un être humain. L’objectif de l’IA est de permettre aux machines de traiter des informations, de résoudre des problèmes, de prendre des décisions, et même d’apprendre par elles-mêmes en utilisant des données et des algorithmes. !"},
    {question: "miboun", response: "c'est un grand mot ,slvp un peut de respect !"},
    {question: "limite", response: "cest un bon question , a ce niveaux je ne peut pas de calculer des opperations mathématiques ,et je ne peut pas corriger des text ,mais jai entrain de corriger ses defaux, et merci pour votre inteligent question!"},
    {question: "votre code", response: "pardon, je ne peut pas repondre a ce question c'est interdit !"},
    {question: "content", response: "je suis ravi datendre ca mon ami !"},
    {question: "contente", response: "je suis ravi datendre ca mon madame !"},
    {question: "trist", response: "Je suis désolé que tu te sentes triste. Parler de ce qui te pèse peut parfois apporter un peu de soulagement, et je suis là si tu veux discuter ou si tu as besoin d'un peu de distraction."},
    {question: "votre age", response: "jait 3 semaines !"},
    {question: "age a tu", response: "jait 3 semaines !"},
    {question: "six sigma", response: "La méthode Six Sigma est une approche systématique visant à améliorer la qualité des processus en réduisant les défauts et les variations. Elle repose sur l'utilisation de données et d'analyses pour identifier et éliminer les sources d'erreurs et améliorer les performances d'un processus. Six Sigma utilise une échelle de mesure basée sur le nombre de défauts par million d'opportunités (DPMO), et l'objectif est d'atteindre un niveau de performance où seulement 3,4 défauts se produisent par million d'opportunités (ce qui correspond à un Six Sigma.Lorsque la méthode Six Sigma est intégrée à la philosophie Lean, qui vise à éliminer les gaspillages et à optimiser l'efficacité des processus, on obtient une approche puissante pour améliorer à la fois la qualité et la productivité. Cette intégration est souvent appelée Lean Six Sigma. !"},
    {question: "Lean management", response: "Le Lean management vise à améliorer l'efficacité en éliminant les gaspillages et en optimisant les processus. Voici les principaux outils utilisés dans cette méthode :5S : Organiser et standardiser les espaces de travail pour améliorer l'efficacité.Kaizen : Amélioration continue avec des changements réguliers et petits proposés par les employés.Value Stream Mapping (VSM) : Cartographier les flux de valeur pour identifier les gaspillages.Juste-à-Temps(JAT) : Produire ou acheter en fonction de la demande pour éviter les stocks excessifs.Kanban : Système de gestion visuelle des flux de travail pour synchroniser la production.Poka-Yoke : Prévenir les erreurs humaines dans les processus.Takt Time : Déterminer le rythme de production pour répondre à la demande du client.SMED : Réduire le temps de changement d'outil pour améliorer la productivité.Pareto (80/20) : Identifier les principales causes de problèmes pour se concentrer sur les plus impactantes.Hoshin Kanri : Aligner les objectifs stratégiques avec les actions quotidiennes.A3 Problem Solving : Résolution de problèmes structurée en une seule page.Lean Six Sigma : Combinaison du Lean et Six Sigma pour améliorer la qualité et réduire les variations.Tous ces outils visent à optimiser les processus, réduire les coûts et améliorer la satisfaction client par l'amélioration continue."},
    {question: "football", response: "Le football est un sport collectif pratiqué entre deux équipes de 11 joueurs, qui s'affrontent sur un terrain rectangulaire pour marquer des buts en envoyant un ballon dans le but adverse. L'objectif est de marquer plus de buts que l'équipe adverse dans un temps déterminé, généralement 90 minutes, réparties en deux mi-temps de 45 minutes chacune. !"},
    {question: "content", response: "je suis ravi d'atendre ca mon monsieux !"},
    {question: "raytchou" , response: "bien sur, cest lami de mon createur , il est de nationalite tunisienne et francaise , il a 10 ans et son anniversaire le 18 décembre,il etude au college fenelon et habite dans SAUNT4AUBIN LES ELBEUF ?il adore ces jeux:pokemon,bakougan et il aime cristiano ronaldo et mbappe et aussi il adore les spaghetti , si vous aimez ces information dit extra !"},
    {question: "content", response: "je suis ravi d'atendre ca mon monsieux !"},
    { question: "machine learning", response: "Le Machine Learning est une branche de l'intelligence artificielle qui permet aux ordinateurs d'apprendre à partir des données sans être explicitement programmés pour chaque tâche." },
    { question: "ordinateur quantique", response: "Les ordinateurs quantiques utilisent les principes de la mécanique quantique pour effectuer des calculs beaucoup plus rapides que les ordinateurs classiques." },
    { question: "chatgpt", response: "ChatGPT est un modèle de langage développé par OpenAI capable de comprendre et de générer du texte en imitant le langage humain." },
    { question: "proverbes tunisiens", response: "Quelques proverbes tunisiens : 'Elli yhebek ybannilk', 'Matyassekch bi sghir la yaamil kbir'." },
    { question: "pays du monde", response: "Les pays du monde incluent la France, la Tunisie, le Japon, les États-Unis, le Brésil, et bien d'autres." },
    { question: "besoin d'aide", response: "Je suis là pour vous aider avec des questions basiques. Que puis-je faire pour vous aujourd'hui ?" },
    { question: "cinéma", response: "Le cinéma est un art et une industrie consacrée à la création de films. Quels types de films aimez-vous ?" },
    { question: "moteurs de recherche", response: "Les moteurs de recherche incluent Google, Bing, Yahoo, et DuckDuckGo." },
    { question: "créer une startup", response: "La création d'une startup implique de trouver une idée innovante, de monter un business plan, de chercher des financements et de développer un produit." },
    { question: "sport en tunisie", response: "Le sport en Tunisie inclut le football, le handball, et la lutte, très appréciés dans le pays." },
    { question: "acteurs", response: "Certains des meilleurs acteurs sont Leonardo DiCaprio, Denzel Washington, Marion Cotillard et Meryl Streep." },
    { question: "espace", response: "L'espace est l'immensité qui s'étend au-delà de l'atmosphère terrestre. Il contient des étoiles, des planètes, des galaxies, et bien plus encore." },
    { question: "vie sur Mars", response: "La possibilité de vie sur Mars est étudiée, bien que pour l'instant, aucune preuve de vie n'ait été trouvée sur la planète rouge." },
    { question: "internet", response: "Internet est un réseau mondial qui relie des milliards d'appareils, permettant l'échange d'informations et la communication globale." },
    { question: "vacances en Tunisie", response: "La Tunisie est célèbre pour ses belles plages, ses ruines historiques, et sa cuisine délicieuse." },
    { question: "cuisine", response: "Certaines cuisines populaires incluent la cuisine italienne, française, japonaise, tunisienne et libanaise." },
    { question: "nouvelles technologies", response: "Les nouvelles technologies incluent la réalité augmentée, l'intelligence artificielle, l'informatique quantique, et la 5G." },
    { question: "fetes en tunisie", response: "En Tunisie, on célèbre l'Aïd, le Ramadan, l'indépendance le 20 mars et la fête de la République le 25 juillet." },
    { question: "applications populaires", response: "Les applications populaires incluent Instagram, WhatsApp, TikTok, et YouTube." },
    { question: "carrière dans l'informatique", response: "Les carrières dans l'informatique incluent le développement de logiciels, la sécurité informatique, l'analyse de données, et l'intelligence artificielle." },
    { question: "alimentation équilibrée", response: "Une alimentation équilibrée fournit tous les nutriments essentiels, y compris les protéines, les glucides, les graisses, les vitamines et les minéraux, en quantité appropriée." },
    { question: "sommeil par nuit", response: "En général, les adultes ont besoin de 7 à 9 heures de sommeil par nuit, mais cela peut varier en fonction de l'âge et des besoins individuels." },
    { question: "grippe", response: "Reposez-vous, buvez beaucoup de liquides, et utilisez des antipyrétiques pour la fièvre si nécessaire. Consultez un médecin si les symptômes s'aggravent." },
    { question: "cholestérol", response: "Le cholestérol est une substance grasse nécessaire au corps, mais un excès de mauvais cholestérol (LDL) peut augmenter le risque de maladies cardiovasculaires." },
    { question: "stress", response: "Pour gérer le stress, essayez la méditation, l'exercice physique, un bon sommeil, et prenez du temps pour des loisirs ou des activités relaxantes." },
    { question: "méditation", response: "La méditation aide à réduire le stress, améliore la concentration, diminue l'anxiété et peut favoriser un sentiment de bien-être général." },
    { question: "système immunitaire", response: "Pour un système immunitaire fort, suivez une alimentation équilibrée, dormez suffisamment, faites de l'exercice régulièrement et évitez le tabac et l'alcool en excès." },
    { question: "masse corporelle (IMC)", response: "L'IMC est un indicateur de la corpulence calculé à partir du poids et de la taille. Il peut aider à évaluer les risques pour la santé liés au surpoids ou à l'insuffisance pondérale." },
    { question: "hydraté", response: "L'hydratation est essentielle pour la digestion, la régulation de la température corporelle, et le bon fonctionnement des organes. Il est recommandé de boire environ 1,5 à 2 litres d'eau par jour." },
    { question: "l'exercice physique", response: "L'exercice aide à améliorer la santé cardiovasculaire, la force musculaire, l'endurance, et peut également avoir des effets positifs sur la santé mentale." },
    { question: "comment réduire la consommation de sucre", response: "Pour réduire le sucre, évitez les boissons sucrées, les collations transformées, et optez pour des fruits frais ou des alternatives à faible teneur en sucre." },
    { question: "oméga-3", response: "Les oméga-3 sont des acides gras bénéfiques pour le cœur et le cerveau. On les trouve dans les poissons gras, les graines de lin, et les noix." },
    { question: "l'hypertension", response: "L'hypertension, ou tension artérielle élevée, est une condition qui peut augmenter le risque de maladies cardiaques et d'AVC. Une alimentation équilibrée et l'exercice peuvent aider à la gérer." },
    { question: "diabète", response: "Le diabète est une maladie chronique où le corps ne peut pas réguler correctement la glycémie, nécessitant une gestion par alimentation, exercice, et parfois médicaments." },
    { question: "le mal de dos", response: "Pour éviter le mal de dos, maintenez une bonne posture, renforcez les muscles du dos et des abdominaux, et évitez de soulever des charges lourdes de manière incorrecte." },
    { question: "santé mentale", response: "La santé mentale est le bien-être émotionnel et psychologique. Prendre soin de sa santé mentale est essentiel pour une vie équilibrée et épanouissante." },
    { question: "dépression", response: "Les symptômes de la dépression incluent une tristesse persistante, une perte d'intérêt, des changements de sommeil, et des difficultés de concentration. Consulter un professionnel est recommandé." },
    { question: "l'anxiété", response: "L'anxiété est une réaction normale au stress, mais lorsqu'elle devient excessive, elle peut nécessiter des techniques de gestion ou une prise en charge médicale." },
    { question: "santé mentale", response: "Entretenez des relations positives, dormez bien, prenez du temps pour des activités que vous aimez, et demandez de l'aide si nécessaire." },
    { question: "symptômes du burn-out", response: "Le burn-out inclut l'épuisement émotionnel, la perte de motivation, l'irritabilité, et des troubles du sommeil. Il est important de se reposer et de parler à un professionnel." },
    { question: "aliments pour une meilleure digestion", response: "Les fibres, les probiotiques (comme le yaourt), les fruits, et les légumes favorisent une bonne digestion." },
    { question: "pleine conscience", response: "La pleine conscience consiste à être pleinement présent et attentif au moment présent, ce qui peut aider à réduire le stress et améliorer le bien-être." },
    { question: "vitamines", response: "Les vitamines sont essentielles au bon fonctionnement du corps. Par exemple, la vitamine C booste le système immunitaire, et la vitamine D est importante pour la santé des os." },
    { question: " rôle du sommeil dans la santé", response: "Le sommeil est crucial pour la récupération physique, la mémoire, et la santé mentale. Un manque de sommeil peut affecter la santé à long terme." },
    { question: "allergie", response: "Une allergie est une réaction excessive du système immunitaire à une substance normalement inoffensive, comme le pollen ou certains aliments." },
    { question: "la santé des yeux", response: "Évitez de fixer les écrans trop longtemps, prenez des pauses régulières, et portez des lunettes de soleil pour protéger vos yeux des UV." },
    { question: "santé bucco-dentaire", response: "La santé bucco-dentaire implique de bonnes habitudes de brossage, l'usage du fil dentaire, et des visites régulières chez le dentiste pour prévenir les caries et autres problèmes." },
    { question: "éviter les maux de tête", response: "Évitez le stress excessif, hydratez-vous bien, et maintenez une bonne posture. Les maux de tête fréquents peuvent nécessiter une consultation médicale." },
    { question: "l'alimentation végétarienne", response: "Une alimentation végétarienne peut réduire le risque de maladies cardiaques, aider à maintenir un poids sain, et avoir des effets bénéfiques pour l'environnement." },
    { question: "démocratie", response: "La démocratie est un système de gouvernement où les citoyens exercent le pouvoir politique en élisant leurs représentants et en participant aux décisions collectives." },
    { question: "constitution", response: "La constitution est un ensemble de règles fondamentales qui définissent l'organisation, les droits et les devoirs d'un État ainsi que les droits des citoyens." },
    { question: "parlement", response: "Le parlement est une institution législative chargée de débattre et de voter les lois, de contrôler le gouvernement et de représenter les citoyens." },
    { question: "fonctions du président", response: "Le président, dans un système présidentiel, est le chef de l'État et souvent du gouvernement, responsable de la politique intérieure et extérieure, de la défense et de la mise en œuvre des lois." },
    { question: "parti politique", response: "Un parti politique est une organisation qui rassemble des individus partageant des idées et des objectifs politiques communs, visant à exercer le pouvoir en participant aux élections." },
    { question: "élection", response: "Une élection est un processus par lequel les citoyens choisissent leurs représentants ou décident d'une question, selon un système de vote." },
    { question: "référendum", response: "Un référendum est une consultation populaire où les citoyens votent pour approuver ou rejeter une proposition de loi ou une décision politique." },
    { question: "république", response: "Une république est un système de gouvernement dans lequel le pouvoir est exercé par des représentants élus, sans monarque héréditaire, et où le chef de l'État est souvent élu." },
    { question: "régime parlementaire", response: "Dans un régime parlementaire, le gouvernement est responsable devant le parlement, et le chef de l'État et le chef du gouvernement sont distincts." },
    { question: "régime présidentiel", response: "Un régime présidentiel est un système où le président est à la fois chef de l'État et chef du gouvernement, exerçant le pouvoir exécutif de manière indépendante du pouvoir législatif." },
    { question: "séparation des pouvoirs", response: "La séparation des pouvoirs est un principe selon lequel les pouvoirs exécutif, législatif et judiciaire sont séparés pour éviter toute concentration de pouvoir." },
    { question: "citoyenneté", response: "La citoyenneté est le statut d'un individu membre d'un État, lui accordant des droits civiques et politiques et impliquant des devoirs envers la société." },
    { question: "l'État de droit", response: "L'État de droit est un principe selon lequel tous les citoyens, y compris les dirigeants, sont soumis aux lois d'un pays, garantissant l'égalité et la justice." },
    { question: "coalition politique", response: "Une coalition politique est une alliance de plusieurs partis ou groupes pour gouverner ensemble, souvent formée en cas de majorité insuffisante au parlement." },
    { question: "scrutin proportionnel", response: "Un scrutin proportionnel est un mode de vote où les sièges sont attribués aux partis en fonction du pourcentage de voix obtenues, reflétant la diversité des opinions." },
    { question: "scrutin majoritaire", response: "Un scrutin majoritaire est un système électoral où le candidat ou le parti ayant le plus de voix l'emporte, souvent utilisé pour renforcer la stabilité gouvernementale." },
    { question: "mandat politique", response: "Un mandat politique est une autorité confiée à une personne élue pour exercer des fonctions au nom des électeurs pour une durée déterminée." },
    { question: "décentralisation", response: "La décentralisation est le transfert de pouvoirs et de responsabilités de l'État central aux collectivités locales pour une gestion plus proche des citoyens." },
    { question: "dictature", response: "Une dictature est un régime politique dans lequel une personne ou un groupe exerce un pouvoir absolu sans opposition ni démocratie." },
    { question: "transparence en politique", response: "La transparence consiste pour les dirigeants à rendre compte de leurs actions et décisions, permettant ainsi au public de comprendre et d'évaluer le fonctionnement de l'État." },
    { question: "lobby", response: "Un lobby est un groupe de pression qui influence les décideurs politiques pour promouvoir les intérêts de ses membres, souvent dans le domaine économique ou social." },
    { question: "l'onu", response: "L'ONU, ou Organisation des Nations Unies, est une organisation internationale qui vise à maintenir la paix, la sécurité, et à promouvoir la coopération entre les pays." },
    { question: "institutions européennes", response: "Les institutions européennes incluent le Parlement européen, le Conseil de l'UE, la Commission européenne, la Cour de justice de l'UE, et d'autres organes de coopération." },
    { question: "ONG", response: "Une ONG, ou organisation non gouvernementale, est une organisation indépendante de l'État, souvent active dans les domaines humanitaire, social ou environnemental." },
    { question: "politique publique", response: "Une politique publique est un ensemble de décisions et d'actions prises par les autorités pour répondre aux besoins ou problèmes de la société." },
    { question: "droit de vote", response: "Le droit de vote est le droit des citoyens de participer aux élections pour choisir leurs représentants ou s'exprimer sur des décisions." },
    { question: "diplomatie", response: "La diplomatie est l'art de gérer les relations internationales par le dialogue et la négociation pour éviter les conflits et renforcer la coopération." },
    { question: "monarchie constitutionnelle", response: "Une monarchie constitutionnelle est un système dans lequel le roi ou la reine est le chef de l'État mais les pouvoirs sont limités par une constitution, et les élus gouvernent." },
    { question: "budget d'État", response: "Le budget de l'État est un document annuel où le gouvernement présente ses prévisions de dépenses et de recettes pour financer les politiques publiques." },
    { question: "relance économique", response: "Un plan de relance économique est un ensemble de mesures destinées à stimuler l'économie, souvent en période de récession, par des investissements et des aides aux secteurs en difficulté." },
    { question: "souveraineté nationale", response: "La souveraineté nationale est le pouvoir exclusif d'un État de gouverner son territoire et de prendre des décisions sans ingérence extérieure." },
    { question: "député", response: "Un député est un représentant élu au sein d'une assemblée législative, chargé de voter les lois et de représenter les citoyens." },
    { question: "sécurité nationale", response: "La sécurité nationale est la protection des citoyens, de l'intégrité territoriale et des intérêts d'un pays contre les menaces extérieures ou intérieures." },
    { question: "changement climatique", response: "Le changement climatique désigne l'augmentation des températures moyennes à l'échelle mondiale, causée par les émissions de gaz à effet de serre provenant de l'activité humaine, avec des impacts sur les écosystèmes et la société." },
    { question: "énergies renouvelables", response: "Les énergies renouvelables proviennent de sources naturelles inépuisables comme le soleil, le vent, l'eau et la biomasse, et permettent de produire de l'énergie sans émettre de gaz à effet de serre." },
    { question: "l'intelligence artificielle", response: "L'intelligence artificielle (IA) est une technologie qui permet aux machines de simuler des capacités humaines comme l'apprentissage, la reconnaissance d'images, la prise de décision et le traitement du langage naturel." },
    { question: "cybersécurité", response: "La cybersécurité est la protection des systèmes informatiques et des réseaux contre les attaques, le vol de données et les accès non autorisés, essentiels dans un monde de plus en plus digitalisé." },
    { question: "blockchain", response: "La blockchain est une technologie de stockage et de transmission de données décentralisée, sécurisée par cryptographie, qui sous-tend des applications comme les cryptomonnaies." },
    { question: "neutralité carbone", response: "La neutralité carbone est l'objectif de réduire les émissions de dioxyde de carbone (CO2) pour compenser les émissions restantes, souvent en les équilibrant par des actions comme la plantation d'arbres." },
    { question: "COVID-19", response: "La pandémie de COVID-19 est une crise sanitaire mondiale causée par le virus SARS-CoV-2, ayant provoqué des millions de décès et des mesures sans précédent pour limiter sa propagation." },
    { question: "vaccination", response: "La vaccination est une méthode de prévention qui introduit un agent pathogène affaibli ou mort dans le corps pour stimuler le système immunitaire et prévenir des maladies spécifiques." },
    { question: "inflation", response: "L'inflation est l'augmentation généralisée et durable des prix des biens et services dans une économie, réduisant le pouvoir d'achat de la monnaie." },
    { question: "transition énergétique", response: "La transition énergétique est le processus de passage d'un système énergétique basé sur les énergies fossiles à un système plus durable, utilisant des énergies renouvelables et réduisant les émissions de carbone." },
    { question: "écologie", response: "L'écologie est la science qui étudie les relations entre les êtres vivants et leur environnement, et est devenue un mouvement pour la préservation de l'environnement." },
    { question: "télétravail", response: "Le télétravail est la possibilité de travailler à distance, souvent depuis chez soi, grâce aux technologies numériques, une pratique devenue courante depuis la pandémie de COVID-19." },
    { question: "métavers", response: "Le métavers est un monde virtuel immersif accessible via internet, où les utilisateurs peuvent interagir, travailler et jouer dans un environnement numérique en 3D." },
    { question: "cryptomonnaie", response: "Une cryptomonnaie est une monnaie numérique sécurisée par la cryptographie, indépendante des banques centrales, et fonctionnant sur la technologie blockchain, comme le Bitcoin." },
    { question: "5G", response: "La 5G est la cinquième génération de réseaux mobiles, offrant des vitesses de connexion plus rapides et permettant le développement de technologies comme l'internet des objets." },
    { question: "réchauffement climatique", response: "Le réchauffement climatique est l'augmentation progressive des températures à l'échelle mondiale, causée par les émissions de gaz à effet de serre dues à l'activité humaine." },
    { question: "désinformation", response: "La désinformation est la diffusion de fausses informations ou d'informations manipulées pour tromper le public ou influencer les opinions." },
    { question: "migration", response: "La migration désigne le déplacement de populations d'un pays à un autre, souvent pour des raisons économiques, politiques ou climatiques." },
    { question: "harcèlement en ligne", response: "Le harcèlement en ligne est un comportement abusif, menaçant ou offensant dirigé contre une personne sur internet, et peut causer des dommages psychologiques importants." },
    { question: "données personnelles", response: "La protection des données personnelles consiste à encadrer la collecte et l'utilisation des informations privées des individus pour garantir leur droit à la vie privée." },
    { question: "économie circulaire", response: "L'économie circulaire vise à réduire le gaspillage en réutilisant et recyclant les ressources pour créer un système plus durable et moins polluant." },
    { question: "pénurie d'eau", response: "La pénurie d'eau est une situation dans laquelle les ressources en eau sont insuffisantes pour répondre aux besoins humains et environnementaux, souvent aggravée par le changement climatique." },
    { question: "inégalité de genre", response: "L'inégalité de genre est la différence de traitement et de possibilités entre les hommes et les femmes, souvent visible dans les domaines de l'emploi, des salaires et de la représentation politique." },
    { question: "précarité énergétique", response: "La précarité énergétique se réfère à l'incapacité d'un ménage à se chauffer correctement à un coût raisonnable, un problème souvent lié aux prix de l'énergie et à la qualité des logements." },
    { question: "justice sociale", response: "La justice sociale est un concept visant à promouvoir l'égalité des droits, des chances et des conditions de vie pour tous, en luttant contre les discriminations et les inégalités." },
    { question: "greenwashing", response: "Le Greenwashing est une stratégie de communication utilisée par certaines entreprises pour se donner une image écologique trompeuse, sans réelles actions environnementales." },
    { question: "big data", response: "Le Big Data fait référence aux grandes quantités de données collectées et analysées par des entreprises et des organisations pour extraire des informations utiles." },
    { question: "égalité des chance", response: "L'égalité des chances est le principe selon lequel chaque individu doit avoir les mêmes opportunités de réussir, indépendamment de son origine, son genre, ou son statut social." },
    { question: "culture numérique", response: "La culture numérique désigne les nouveaux comportements et modes de communication apparus avec le développement des technologies numériques et d'internet." },
    { question: "activisme climatique", response: "L'activisme climatique est un mouvement de citoyens qui militent pour des actions immédiates et significatives contre le changement climatique." },
    { question: "empreinte carbone", response: "L'empreinte carbone est la quantité de gaz à effet de serre émise par une personne, une organisation ou une activité, mesurant son impact sur le réchauffement climatique." },
    { question: "inclusion numérique", response: "L'inclusion numérique est le processus de garantir l'accès aux technologies et compétences numériques pour tous, réduisant ainsi les fractures sociales." },
    { question: "animaux", response: "Les animaux sont des êtres vivants comme les chiens, les chats, les oiseaux, et les poissons. Ils peuvent vivre dans des forêts, des océans, ou même à la maison comme animaux de compagnie !" },
    { question: "planète", response: "Il y a huit planètes dans notre système solaire, comme la Terre où nous vivons, et d’autres comme Mars et Jupiter. Le Soleil est une étoile qui donne de la lumière et de la chaleur aux planètes !" },
    { question: "dinosaure", response: "Les dinosaures sont des animaux préhistoriques qui vivaient il y a des millions d'années. Certains étaient très grands comme le T-Rex, et ils ont disparu avant l'arrivée des humains." },
    { question: "corps humain", response: "Le corps humain est incroyable ! Il est composé de nombreux organes, comme le cœur qui pompe le sang, et les poumons qui nous aident à respirer." },
    { question: "alphabet", response: "L'alphabet est une série de lettres de A à Z. Il est utilisé pour écrire des mots et apprendre à lire. Chaque lettre a un son qui aide à lire les mots !" },
    { question: "météo", response: "La météo peut être ensoleillée, pluvieuse, ou même neigeuse ! Elle change tous les jours et dépend de la saison." },
    { question: "invention", response: "Les inventions sont des créations qui nous aident dans la vie, comme les voitures, les téléphones et même les ordinateurs." },
    { question: "amitié", response: "L'amitié, c'est quand on est amis avec quelqu'un. Les amis jouent ensemble, partagent des moments et s'entraident." },
    { question: "musique", response: "La musique est un mélange de sons et de rythmes. On peut jouer de la musique avec des instruments comme le piano, la guitare et la batterie." },
    { question: "dinosaure", response: "Les dinosaures étaient de grands animaux qui vivaient il y a très longtemps. Certains étaient très grands, comme le T-Rex !" },
    { question: "joie", response: "La joie est une émotion qui nous fait sourire. On ressent de la joie quand on est content ou quand on fait des choses qu'on aime !" },
    { question: "coloriage", response: "Le coloriage est une activité amusante où on colorie des dessins avec des crayons de couleur ou des feutres. C'est génial pour la créativité !" },
    { question: "histoire", response: "Les histoires sont des récits d'aventures ou de leçons, comme les contes de fées ou les légendes. Elles nous font rêver et apprendre !" },
    { question: "écologie", response: "L'écologie est la protection de la nature et des animaux. Recycler et économiser l'eau sont des gestes écologiques !" },
    { question: "robot", response: "Les robots sont des machines qui peuvent faire des choses pour nous, comme nettoyer ou même jouer de la musique !" },
    { question: "vacance", response: "Les vacances sont des moments où on peut se reposer, jouer, et faire des activités amusantes en famille." },
    { question: "fleur", response: "Les fleurs sont belles et colorées. Elles poussent dans les jardins et les forêts, et certaines ont de bonnes odeurs !" },
    { question: "pompier", response: "Les pompiers sont des héros qui éteignent les feux et sauvent les gens en danger. Ils sont très courageux et aident beaucoup de gens !" },
    { question: "métier", response: "Il y a plein de métiers comme enseignant, médecin, ou cuisinier. Chaque métier est important et aide les gens dans leur quotidien." },
    { question: "sécurité internet", response: "Sur Internet, il faut faire attention et ne pas parler aux inconnus. Parle toujours avec un adulte avant de visiter un nouveau site." },
    { question: "dessin animé", response: "Les dessins animés sont des histoires amusantes en images. On y voit des personnages comme Mickey Mouse, les Minions, et bien d'autres !" },
    { question: "mickey mouse", response: "Mickey Mouse est un célèbre personnage de dessin animé créé par Disney. Il a de grandes oreilles rondes et vit plein d'aventures amusantes avec ses amis !" },
    { question: "peppa pig", response: "Peppa Pig est un dessin animé sur une petite cochonne qui vit plein d'aventures avec sa famille et ses amis. C'est très drôle !" },
    { question: "pokemon", response: "Pokémon raconte l'histoire de Sacha et de Pikachu, son Pokémon, qui partent à l'aventure pour attraper des Pokémon et devenir les meilleurs dresseurs." },
    { question: "paw patrol", response: "Paw Patrol, ou La Pat'Patrouille, suit des chiots héros qui aident les gens de leur ville. Chaque chiot a une mission spéciale !" },
    { question: "reine des neiges", response: "La Reine des Neiges raconte l'histoire d'Elsa, une princesse avec des pouvoirs de glace, et de sa sœur Anna. Leur aventure est pleine de magie et de chansons !" },
    { question: "tom et jerry", response: "Tom et Jerry sont un chat et une souris qui adorent se courir après. C'est un dessin animé drôle avec beaucoup de poursuites !" },
    { question: "miraculous", response: "Miraculous est l'histoire de Ladybug et Chat Noir, des super-héros de Paris qui combattent les méchants tout en vivant des aventures passionnantes." },
    { question: "super héros", response: "Les super-héros sont des personnages forts et courageux comme Superman, Batman, et Spider-Man. Ils protègent les gens contre les méchants." },
    { question: "spiderman", response: "Spider-Man est un super-héros qui peut grimper aux murs et lancer des toiles d'araignée. Il protège sa ville des méchants !" },
    { question: "disney", response: "Les films Disney sont des histoires magiques et amusantes, comme Aladdin, Le Roi Lion, et La Petite Sirène." },
    { question: "minions", response: "Les Minions sont des petits personnages jaunes et rigolos. Ils adorent les bananes et font souvent des bêtises !" },
    { question: "spongebob", response: "SpongeBob est une éponge qui vit sous la mer et travaille au Krusty Krab. Il vit plein d'aventures drôles avec son ami Patrick !" },
    { question: "pat patrouille", response: "La Pat' Patrouille est un groupe de chiots courageux qui résolvent des problèmes et aident les gens de leur ville." },
    { question: "dora l'exploratrice", response: "Dora est une petite fille qui part en aventure avec son sac à dos et son ami Babouche le singe. Elle apprend de nouvelles choses à chaque épisode !" },
    { question: "roi lion", response: "Le Roi Lion raconte l'histoire de Simba, un lionceau qui doit apprendre à devenir roi après son père, Mufasa." },
    { question: "winnie l'ourson", response: "Winnie l'Ourson est un ours jaune qui adore le miel. Il vit dans la Forêt des Rêves Bleus avec ses amis comme Porcinet et Tigrou." },
    { question: "titeuf", response: "Titeuf est un dessin animé drôle sur un garçon avec une mèche blonde. Il vit plein de petites aventures avec ses amis." },
    { question: "scooby doo", response: "Scooby-Doo est un chien qui aide ses amis à résoudre des mystères effrayants. Ils voyagent dans leur van Mystère Machine !" },
        { question: "sboui", response: "Sbou3i est un personnage très drôle de la série tunisienne *Choufli Hal*. Il est connu pour ses blagues et son humour unique !" },
        { question: "qui est sboui", response: "Sbou3i est un personnage comique dans *Choufli Hal*, une série tunisienne. Il est maladroit, rigolo, et fait rire tout le monde avec ses histoires." },
        { question: "amis de sboui", response: "Sbou3i a plusieurs amis dans *Choufli Hal*, comme Hassouna et son patron Sboui. Ils se retrouvent souvent pour vivre des situations amusantes." },
        { question: "série de sboui", response: "*Choufli Hal* est une série comique tunisienne où Sbou3i vit plein d'aventures avec sa famille et ses amis." },
        { question: "famous quote sboui", response: "Sbou3i est connu pour sa phrase : 'C'est toi ?' Il l'utilise souvent dans des situations rigolotes." },
        { question: "sbou3i aime", response: "Sbou3i aime manger, faire des blagues, et passer du temps avec ses amis. Il est toujours de bonne humeur !" },
            { question: "sbou3i", response: "Sbou3i est un personnage très drôle de la série tunisienne *Choufli Hal*. Il est connu pour ses blagues et son humour unique !" },
            { question: "qui est sbou3i", response: "Sbou3i est un personnage comique dans *Choufli Hal*, une série tunisienne. Il est maladroit, rigolo, et fait rire tout le monde avec ses histoires." },
            { question: "amis de sbou3i", response: "Sbou3i a plusieurs amis dans *Choufli Hal*, comme Hassouna et son patron Sboui. Ils se retrouvent souvent pour vivre des situations amusantes." },
            { question: "série de sbou3i", response: "*Choufli Hal* est une série comique tunisienne où Sbou3i vit plein d'aventures avec sa famille et ses amis." },
            { question: "famous quote sbou3i", response: "Sbou3i est connu pour sa phrase : 'C'est toi ?' Il l'utilise souvent dans des situations rigolotes." },
            { question: "sbou3i aime", response: "Sbou3i aime manger, faire des blagues, et passer du temps avec ses amis. Il est toujours de bonne humeur !" },
            { question: "football", response: "Le football est un sport collectif où deux équipes de 11 joueurs s'affrontent pour marquer des buts. C'est un sport très populaire dans le monde entier !" },
            { question: "gagné la coupe du monde", response: "La Coupe du Monde de la FIFA est un tournoi de football international. Le dernier vainqueur était l'Argentine en 2022, après avoir battu la France en finale !" },
            { question: "messi", response: "Lionel Messi est un joueur de football argentin, considéré comme l'un des meilleurs joueurs de l'histoire. Il a remporté de nombreux prix, dont plusieurs Ballons d'Or." },
            { question: "ronaldo", response: "Cristiano Ronaldo est un joueur de football portugais célèbre pour sa puissance, sa vitesse et ses buts incroyables. Il a joué pour des clubs comme Manchester United, Real Madrid et la Juventus." },
            { question: "basketball", response: "Le basketball est un sport où deux équipes de cinq joueurs essaient de marquer des points en lançant un ballon dans un panier. Michael Jordan est l'un des plus grands joueurs de ce sport." },
            { question: "tennis", response: "Le tennis est un sport individuel ou en double où les joueurs utilisent une raquette pour frapper une balle par-dessus un filet. Roger Federer, Rafael Nadal et Novak Djokovic sont des légendes du tennis." },
            { question: "olympiques", response: "Les Jeux Olympiques sont un événement sportif international où des athlètes du monde entier s'affrontent dans différentes disciplines comme l'athlétisme, la natation, le football et bien d'autres." },
            { question: "sports populaires", response: "Les sports les plus populaires dans le monde sont le football, le basketball, le tennis, le cricket, et le rugby. Chacun d'eux a des millions de fans à travers le monde !" },
            { question: "cjouer au foot", response: "Pour jouer au football, il suffit de dribbler le ballon, de le passer à tes coéquipiers, et de tenter de marquer des buts dans le but adverse ! N'oublie pas de respecter les règles et de t'amuser." },
            { question: "sports d'équipe", response: "Le football, le basketball, le rugby et le volleyball sont des sports d'équipe où il faut collaborer avec les autres joueurs pour gagner." },
            { question: "sports d'individuel", response: "Le tennis, la natation, le cyclisme et l'athlétisme sont des sports individuels où chaque joueur ou athlète s'affronte seul." },
            { question: "ballon d'or", response: "Le Ballon d'Or est un prix décerné chaque année au meilleur joueur de football du monde. Il a été remporté plusieurs fois par Lionel Messi et Cristiano Ronaldo." },
            { question: "michael jordan", response: "Michael Jordan est un ancien joueur de basketball américain, considéré comme le plus grand joueur de basketball de tous les temps. Il a joué pour les Chicago Bulls et a remporté six championnats NBA." },
            { question: "jouer au basketball", response: "Pour jouer au basketball, tu dois dribbler le ballon avec tes mains et essayer de marquer en lançant le ballon dans le panier. C'est un sport rapide et amusant!" },
            { question: "sports d'hiver", response: "Les sports d'hiver incluent le ski, le snowboard, le patinage et le hockey sur glace. Ces sports sont pratiqués dans des endroits froids et enneigés." },
            { question: "albert einstein", response: "Albert Einstein était un physicien théoricien allemand, célèbre pour sa théorie de la relativité. Il a remporté le prix Nobel de physique en 1921 et est considéré comme l'un des plus grands scientifiques de l'histoire." },
            { question: "nelson mandela", response: "Nelson Mandela était un homme politique sud-africain, militant pour les droits de l'homme et l'égalité. Il a lutté contre l'apartheid en Afrique du Sud et est devenu le premier président noir du pays." },
            { question: "winston churchill", response: "Winston Churchill était le Premier ministre du Royaume-Uni pendant la Seconde Guerre mondiale. Il est célèbre pour son courage et ses discours inspirants, qui ont motivé son pays pendant la guerre." },
            { question: "martin luther king", response: "Martin Luther King Jr. était un pasteur et militant américain, connu pour sa lutte pacifique contre la ségrégation raciale et pour les droits civils. Son discours 'I Have a Dream' est l'un des plus célèbres de l'histoire." },
            { question: "mahatma gandhi", response: "Mahatma Gandhi était un leader indien qui a lutté pour l'indépendance de l'Inde en utilisant la résistance non violente. Il est connu pour sa philosophie de la non-violence et de la vérité." },
            { question: "leonardo da vinci", response: "Leonardo da Vinci était un génie italien de la Renaissance, connu pour ses œuvres artistiques comme la 'Mona Lisa' et 'La Cène', ainsi que pour ses inventions et ses découvertes dans des domaines variés." },
            { question: "abraham lincoln", response: "Abraham Lincoln était le 16e président des États-Unis. Il est célèbre pour avoir aboli l'esclavage et avoir dirigé le pays pendant la guerre civile américaine." },
            { question: "steve jobs", response: "Steve Jobs était un entrepreneur américain, co-fondateur d'Apple. Il est connu pour avoir révolutionné l'industrie de la technologie avec des produits comme l'iPhone, l'iPad et le Mac." },
            { question: "barack obama", response: "Barack Obama était le 44e président des États-Unis et le premier président afro-américain. Il a travaillé pour l'égalité, la santé publique, et a reçu le prix Nobel de la paix en 2009." },
            { question: "leonardo diCaprio", response: "Leonardo DiCaprio est un acteur américain célèbre pour ses rôles dans des films comme 'Titanic', 'Inception', et 'The Revenant'. Il est également un défenseur de l'environnement." },
            { question: "muhammad ali", response: "Muhammad Ali était un boxeur américain, considéré comme l'un des plus grands boxeurs de tous les temps. Il a remporté trois fois le titre mondial des poids lourds." },
            { question: "thomas edison", response: "Thomas Edison était un inventeur américain, célèbre pour avoir inventé l'ampoule électrique. Il a déposé plus de 1 000 brevets pour ses inventions." },
            { question: "elon musk", response: "Elon Musk est un entrepreneur et ingénieur sud-africain. Il est connu pour avoir fondé des entreprises comme Tesla et SpaceX, avec des projets ambitieux pour l'avenir de l'énergie et de l'exploration spatiale." },
            { question: "william shakespeare", response: "William Shakespeare était un dramaturge et poète anglais, considéré comme l'un des plus grands écrivains de tous les temps. Il a écrit des pièces comme 'Roméo et Juliette' et 'Hamlet'." },
            { question: "christopher columbus", response: "Christophe Colomb était un explorateur italien, célèbre pour avoir 'découvert' l'Amérique en 1492, bien qu'il n'ait pas été le premier à atteindre ce continent." },    

            { question: "Qui es-tu ?", response: "Je suis HBA, un assistant virtuel créé pour répondre à vos questions et vous aider avec des informations variées." },
            { question: "Comment ça marche ?", response: "Il suffit de me poser une question, et je ferai de mon mieux pour y répondre. Vous pouvez poser des questions sur n'importe quel sujet !" },
            { question: "tu faire", response: "Je peux répondre à des questions, donner des informations sur divers sujets, discuter de différents thèmes, et même vous donner des conseils ou des recommandations." },
            { question: "t'utiliser", response: "Il suffit de poser une question et j'y répondrai de manière aussi précise et utile que possible !" },
            { question: "Peux-tu m'aider avec mes devoirs", response: "Je peux vous fournir des informations pour vous aider à comprendre vos devoirs, mais je ne peux pas faire les devoirs à votre place." },
            { question: "l'intelligence artificielle", response: "L'intelligence artificielle (IA) est un domaine de l'informatique qui cherche à créer des machines capables d'effectuer des tâches qui nécessitent normalement l'intelligence humaine, comme résoudre des problèmes ou prendre des décisions." },
            { question: "apprendre une langue", response: "Oui, je peux vous donner des conseils, des ressources et même vous aider avec des traductions ou des exercices." },
            { question: "meilleurs films", response: "Cela dépend de vos goûts ! Si vous aimez l'action, vous pourriez aimer 'Avengers'. Si vous aimez les films d'animation, essayez 'Toy Story' ou 'Le Roi Lion'." },
            { question: "raconter une histoire ", response: "Bien sûr ! Quelle genre d'histoire aimeriez-vous ? Une histoire de prince et de princesse, un conte fantastique, ou quelque chose d'autre ?" },
            { question: "livre préféré", response: "En tant qu'IA, je n'ai pas de préférences, mais je peux vous recommander des livres populaires comme 'Harry Potter' ou 'Le Petit Prince'." },
            { question: "meilleur jeu vidéo ", response: "Il existe de nombreux excellents jeux vidéo, comme 'Minecraft' pour la créativité, 'Fortnite' pour l'action, et 'The Legend of Zelda' pour l'aventure." },
            { question: "résoudre des mathématiques", response: "pardon, je ne peux pas vous aider à résoudre des problèmes mathématiques." },
            { question: "ma prochaine fête", response: "Je ne peux pas connaître vos dates de fête, mais je peux vous aider à organiser des événements ou vous rappeler des dates importantes si vous me les donnez !" },
            { question: "pays le plus grand", response: "Le plus grand pays du monde par superficie est la Russie." },
            { question: "inventé l'ordinateur", response: "L'ordinateur moderne a été inventé par de nombreuses personnes. Charles Babbage est souvent considéré comme le 'père de l'ordinateur'." },
            { question: "signifie IA", response: "IA signifie 'Intelligence Artificielle'. C'est une branche de l'informatique qui se concentre sur la création de machines capables d'apprendre et de résoudre des problèmes de manière autonome." },
            { question: "le ciel est bleu", response: "Le ciel est bleu à cause de la façon dont la lumière du soleil interagit avec l'atmosphère. La lumière bleue se diffuse plus que les autres couleurs, c'est pour ça que nous voyons le ciel bleu." },
            { question: "oiseaux volent", response: "Les oiseaux volent grâce à leurs ailes qui leur permettent de générer une portance. Cela les aide à se déplacer dans l'air." },
            { question: "donner une recette", response: "Bien sûr ! Si vous avez un plat en tête, je peux vous fournir une recette. Par exemple, pour des cookies, vous aurez besoin de farine, de sucre, de beurre, etc." },
            { question: "située la France", response: "La France est située en Europe de l'Ouest, bordée par la mer Méditerranée au sud et l'océan Atlantique à l'ouest." },
            { question: "Peux-tu m'aider à programmer ?", response: "Oui, je peux vous aider avec des conseils de programmation en différents langages comme Python, JavaScript, et plus encore." },
            { question: "big bang", response: "Le Big Bang est la théorie qui décrit la naissance de l'univers il y a environ 13,8 milliards d'années, lorsqu'un point extrêmement dense et chaud a commencé à se dilater et à se refroidir." },
            { question: "idée de cadeau", response: "Bien sûr ! Pour un anniversaire, vous pouvez offrir des jeux vidéo, des livres, ou même des expériences comme des parcs d'attractions." },
            { question: "Terre a été formée", response: "La Terre s'est formée il y a environ 4,5 milliards d'années, à partir de gaz et de poussières qui ont fusionné pour créer notre planète." },
            { question: "que l'espace", response: "L'espace est l'étendue infinie qui se trouve au-delà de l'atmosphère terrestre. C'est un endroit où se trouvent les étoiles, les planètes, les galaxies et tout ce qui constitue l'univers." },

            { question: "en Palestine ", response: "La situation en Palestine est complexe et en constante évolution. Le conflit Israël-Palestine continue d'avoir des répercussions humanitaires graves, avec des appels internationaux à la paix et à la négociation." },
            { question: "conflit israel palestine ", response: "Les récents événements ont intensifié les tensions. Des efforts diplomatiques sont en cours pour trouver une solution pacifique, mais la situation reste très tendue." },
            { question: "lutter contre le changement climatique ", response: "De nombreux pays ont pris des engagements pour réduire les émissions de gaz à effet de serre, notamment en augmentant l'utilisation des énergies renouvelables et en soutenant la transition vers une économie verte." },
            { question: "gouvernement pour améliorer l'éducation en [pays] ", response: "Des réformes éducatives sont en cours, visant à améliorer l'accès à l'éducation de qualité, en particulier dans les régions défavorisées, ainsi qu'à promouvoir l'apprentissage numérique." },
            { question: "améliorer l'égalité des genres dans le monde ", response: "Des campagnes mondiales pour la parité salariale, la protection contre la violence domestique et la promotion des droits des femmes sont en cours dans plusieurs pays." },
            { question: "initiatives pour la préservation de la biodiversité ", response: "Des programmes mondiaux comme la création de nouvelles réserves naturelles, l'interdiction de certaines pratiques destructrices et l'augmentation du financement de la recherche sur la biodiversité ont été mis en place." },
            { question: "Que fait l'ONU ", response: "L'ONU met en œuvre des programmes d'aide humanitaire pour les réfugiés et les déplacés internes, tout en travaillant à des solutions diplomatiques pour réduire les conflits qui les génèrent." },
            { question: "progrès dans la lutte contre la pandémie de COVID-19", response: "Des campagnes de vaccination mondiales sont en cours pour réduire la propagation du virus, et des efforts sont faits pour mieux préparer les systèmes de santé aux futures pandémies." },
            { question: "soutenir les populations touchées par les catastrophes naturelles ", response: "Des programmes d'urgence sont lancés pour fournir des secours immédiats, et des stratégies de résilience à long terme sont développées pour mieux répondre aux catastrophes futures." },
            { question: "gouvernements gèrent ils les défis économiques actuels", response: "Les gouvernements adoptent des politiques de soutien à l'économie, telles que des plans de relance, des réductions fiscales et des investissements dans les infrastructures." },
            { question: "initiatives pour lutter contre la pauvreté", response: "Des programmes d'assistance sociale, des initiatives pour améliorer l'accès à l'éducation et à la santé, ainsi que des politiques économiques de soutien aux familles défavorisées sont en place." },
            { question: "politiques environnementales dans pays", response: "Les nouvelles politiques environnementales visent à réduire les émissions de carbone, à protéger les ressources naturelles et à promouvoir un développement durable." },
            { question: "négociations de paix en région ou pays", response: "Les négociations de paix sont en cours, avec des pourparlers entre les parties concernées, soutenus par des médiateurs internationaux." },
            { question: "actions sont entreprises pour soutenir les travailleurs et les entreprises pendant la crise économique", response: "Des mesures telles que des subventions aux entreprises, des programmes de formation pour les travailleurs et des allocations de chômage temporaires sont mises en place." },
            { question: "Comment la communauté internationale réagit-elle à la crise des droits de l'homme en pays", response: "Des pressions diplomatiques et des sanctions sont imposées contre les responsables des violations des droits de l'homme, tout en soutenant les victimes." },
            { question: "réduire les inégalités dans les soins de santé mondiaux", response: "Des programmes internationaux visent à améliorer l'accès aux soins de santé dans les pays en développement, notamment par des campagnes de vaccination et des investissements dans les infrastructures sanitaires." },
            { question: "grandes entreprises pour réduire leur empreinte carbone", response: "Les entreprises adoptent des pratiques plus écologiques, comme l'utilisation de sources d'énergie renouvelable, la réduction des déchets et la compensation des émissions de carbone." },
            { question: "avancées dans la technologie verte", response: "Des innovations dans les énergies renouvelables, les véhicules électriques et l'architecture durable font partie des dernières avancées technologiques pour la protection de l'environnement." },
            { question: "initiatives pour encourager le recyclage et la gestion des déchets", response: "Des programmes de recyclage à grande échelle sont lancés, visant à réduire les déchets et à promouvoir l'économie circulaire." },
            { question: "lutter contre la corruption", response: "Des lois plus strictes, des programmes de transparence et des partenariats internationaux sont mis en place pour réduire la corruption à tous les niveaux." },
            { question: "Comment les politiques d'immigration ont-elles évolué", response: "Les politiques d'immigration ont évolué pour équilibrer les besoins économiques des pays et la protection des droits des migrants." },

            { question: "le codage", response: "Le codage (ou programmation) consiste à écrire des instructions pour que les ordinateurs puissent exécuter des tâches spécifiques. Ces instructions sont écrites dans des langages de programmation comme Python, JavaScript, Java, etc." },
            { question: "Quel langage de programmation dois je apprendre en premier", response: "Le langage Python est souvent recommandé pour les débutants en raison de sa syntaxe simple et de son utilisation dans divers domaines comme le développement web, l'intelligence artificielle et l'analyse de données." },
            { question: "apprendre le codage", response: "Il existe de nombreuses ressources gratuites en ligne pour apprendre à coder, telles que des tutoriels sur YouTube, des cours en ligne sur des plateformes comme Codecademy, Coursera, ou Khan Academy." },
            { question: "algorithme", response: "Un algorithme est une série d'instructions ou de règles à suivre pour résoudre un problème ou accomplir une tâche spécifique, comme trier une liste de nombres." },
            { question: "langage de programmation", response: "Un langage de programmation est un moyen de communiquer avec un ordinateur. Chaque langage a ses propres règles de syntaxe et de structure, comme Python, JavaScript, ou C++." },
            { question: "différence entre Python et JavaScript", response: "Python est souvent utilisé pour l'analyse de données, l'intelligence artificielle et les scripts côté serveur, tandis que JavaScript est principalement utilisé pour le développement web, notamment pour ajouter des interactions sur des pages web." },
            { question: "variables en programmation", response: "Les variables sont des espaces de stockage dans un programme qui contiennent des valeurs. Ces valeurs peuvent changer au cours de l'exécution du programme." },
            { question: "une fonction", response: "Une fonction est un bloc de code qui effectue une tâche spécifique. Elle peut être appelée à plusieurs reprises dans un programme pour éviter la répétition du même code." },
            { question: "que le débogage", response: "Le débogage est le processus de recherche et de correction des erreurs (bugs) dans le code. Cela implique généralement d'exécuter le programme et d'analyser son comportement pour identifier où il échoue." },
            { question: "pourquoi le codage est il important", response: "Le codage est essentiel dans le monde numérique moderne car il permet de créer des logiciels, des applications et des sites web. Il est également crucial dans des domaines comme la cybersécurité, la data science, et l'intelligence artificielle." },
            { question: "développement logiciel", response: "L'intégration continue est une pratique qui consiste à fusionner régulièrement les modifications de code dans un dépôt central, où elles sont testées automatiquement pour détecter rapidement des erreurs." },
            { question: "Git et GitHub", response: "Git est un système de gestion de versions qui permet de suivre l'historique des modifications d'un projet. GitHub est une plateforme en ligne qui permet de stocker et de partager des projets Git." },
            { question: "développement web", response: "Le développement web consiste à créer et à maintenir des sites web. Cela inclut le codage côté client (HTML, CSS, JavaScript) pour l'interface utilisateur, et côté serveur (comme Node.js, PHP, ou Ruby) pour le traitement des données." },
            { question: "une API", response: "Une API (Interface de Programmation d'Application) est un ensemble de règles et de spécifications que les programmes peuvent suivre pour interagir les uns avec les autres. Par exemple, une API peut permettre à une application mobile de récupérer des données depuis un serveur." },
            { question: "framework", response: "Un framework est un ensemble d'outils, de bibliothèques et de conventions de codage qui simplifie le développement d'applications. Par exemple, Django pour Python et React pour JavaScript." },
            { question: "cloud computing", response: "Le cloud computing permet d'accéder à des ressources informatiques (comme des serveurs, des bases de données, des logiciels, etc.) via Internet, sans avoir à gérer de matériel physique." },
            { question: "base de données", response: "Une base de données est un système organisé pour collecter, stocker et gérer des données. Les bases de données sont utilisées pour gérer de grandes quantités d'informations, comme celles des utilisateurs ou des transactions." },
            { question: "tests unitaires", response: "Les tests unitaires sont des tests automatisés effectués pour vérifier si chaque composant individuel d'un programme fonctionne correctement." },
            { question: "programmation orientée objet", response: "La programmation orientée objet (POO) est un paradigme de programmation qui organise le code autour d'objets, qui sont des instances de classes. Chaque objet contient des données et des méthodes pour manipuler ces données." },
            { question: "un ide", response: "Un IDE (Environnement de Développement Intégré) est un logiciel qui fournit des outils pour écrire, tester et déboguer du code. Des exemples populaires sont Visual Studio Code, PyCharm et Eclipse." },

            { question: "application mobile", response: "Une application mobile est un programme conçu pour fonctionner sur des appareils mobiles, comme un smartphone ou une tablette. Elle peut être utilisée pour accomplir diverses tâches, comme la navigation, la gestion de tâches, ou le divertissement." },
            { question: "application web", response: "Une application web est un programme accessible via un navigateur internet, qui fonctionne sur un serveur distant. Contrairement aux applications mobiles, elle ne nécessite pas de téléchargement sur l'appareil." },
            { question: "créer une application mobile", response: "La création d'une application mobile nécessite des compétences en développement, notamment dans des langages comme Java pour Android ou Swift pour iOS. Il est aussi possible d'utiliser des outils de développement multiplateformes comme Flutter ou React Native." },
            { question: "le coût pour développer une application", response: "Le coût de développement d'une application varie en fonction de sa complexité, des fonctionnalités, et de la plateforme choisie. Les prix peuvent aller de quelques milliers à plusieurs centaines de milliers de dollars." },
            { question: "application native", response: "Une application native est une application développée spécifiquement pour une plateforme (par exemple, Android ou iOS) en utilisant les outils et langages natifs de cette plateforme." },
            { question: "application hybride", response: "Une application hybride combine les caractéristiques des applications natives et des applications web. Elle peut fonctionner sur plusieurs plateformes (Android, iOS) grâce à un seul code base écrit dans des langages comme HTML, CSS, et JavaScript." },
            { question: "application PWA", response: "Une PWA (Progressive Web App) est une application qui utilise des technologies web modernes pour offrir une expérience similaire à une application native, tout en étant accessible via un navigateur." },
            { question: "publier une application sur l'App Store ou Google Play", response: "Pour publier une application, il faut d'abord créer un compte développeur sur l'App Store (Apple) ou Google Play. Ensuite, vous devez soumettre votre application après l'avoir testée et vous assurer qu'elle respecte les lignes directrices des stores." },
            { question: "cycle de vie d'une application", response: "Le cycle de vie d'une application fait référence aux différentes étapes par lesquelles une application passe, de sa conception et son développement à son lancement, sa mise à jour et sa maintenance." },
            { question: "API dans une application", response: "Une API (Interface de Programmation d'Applications) permet à une application de communiquer avec d'autres applications ou services. Par exemple, une application de météo peut utiliser une API pour récupérer des informations météo en temps réel." },
            { question: "backend application", response: "Le backend d'une application désigne la partie de l'application qui gère les bases de données, les serveurs, et la logique de traitement des données, par opposition à l'interface utilisateur (frontend)." },
            { question: "frontend application", response: "Le frontend d'une application est la partie visible de l'application avec laquelle l'utilisateur interagit. Il inclut les éléments d'interface comme les boutons, les menus et les écrans." },
            { question: "tester une application", response: "Tester une application est essentiel pour garantir qu'elle fonctionne correctement, qu'elle est sécurisée et qu'elle répond aux besoins des utilisateurs. Cela permet d'éviter des erreurs qui pourraient nuire à l'expérience utilisateur ou à la réputation de l'application." },
            { question: "test bêta", response: "Un test bêta est une phase de test où une version préliminaire de l'application est rendue disponible à un groupe restreint d'utilisateurs pour recueillir leurs retours avant la sortie officielle." },
            { question: "compatibilité multiplateforme", response: "La compatibilité multiplateforme fait référence à la capacité d'une application à fonctionner sur plusieurs plateformes (par exemple, Android et iOS) avec le même code source." },
            { question: "responsive design pour les applications", response: "Le responsive design est une approche de conception qui permet à une application de s'adapter et de s'ajuster à différentes tailles d'écran et résolutions, offrant ainsi une expérience utilisateur optimale, quel que soit l'appareil." },
            { question: "outil pour créer des applications", response: "Il existe plusieurs outils de développement pour créer des applications, tels que Xcode pour iOS, Android Studio pour Android, ainsi que des frameworks multiplateformes comme Flutter, React Native, et Xamarin." },
            { question: "notifications push dans les applications", response: "Les notifications push sont des messages envoyés par une application à l'utilisateur, même lorsque celle-ci n'est pas ouverte. Elles peuvent être utilisées pour des alertes, des mises à jour ou des promotions." },
            { question: "store applications", response: "Un store d'applications est une plateforme en ligne où les utilisateurs peuvent télécharger et installer des applications. Les deux principaux stores sont l'App Store d'Apple et Google Play pour Android." },
            { question: "monétisation d'une application", response: "La monétisation d'une application consiste à générer des revenus à partir de celle-ci. Cela peut se faire via la vente de l'application, la publicité, des achats in-app, ou un abonnement premium." },

            { question: "méthodes d'apprentissage", response: "Les meilleures méthodes d'apprentissage incluent la répétition espacée, la pratique active, la prise de notes, l'auto-évaluation et l'utilisation de supports visuels et interactifs pour renforcer la compréhension." },
            { question: "sites d'éducation en ligne", response: "Les meilleurs sites d'éducation en ligne incluent Khan Academy, Coursera, edX, Takyacademi.tn, et lyceena.tn pour des cours dans divers domaines." },
            { question: "choisir une bonne école", response: "Pour choisir une bonne école, il est important de considérer les programmes, la qualité des enseignants, les installations, les résultats aux examens, et les avis des anciens élèves." },
            { question: "avantage de l'apprentissage en ligne", response: "L'apprentissage en ligne offre la flexibilité d'apprendre de n'importe où, des cours personnalisés, un accès à des ressources variées, et souvent des coûts réduits." },
            { question: "éducation est elle importante", response: "L'éducation est cruciale pour le développement personnel, professionnel, et social. Elle favorise la connaissance, les compétences et la pensée critique, permettant aux individus de contribuer positivement à la société." },
            { question: "éducation inclusive", response: "L'éducation inclusive vise à permettre à tous les enfants, y compris ceux avec des besoins spéciaux, d'accéder à une éducation de qualité dans un environnement adapté à leurs besoins." },
            { question: "gérer le stress des examens", response: "Pour gérer le stress des examens, adoptez des habitudes de révision régulières, prenez des pauses, dormez bien, mangez sainement, et pratiquez des techniques de relaxation comme la respiration profonde." },
            { question: "compétences les plus recherchées en 2024", response: "Les compétences les plus recherchées incluent la pensée critique, la résolution de problèmes, les compétences en communication, la maîtrise des technologies numériques, et la capacité d'adaptation." },
            { question: "défis de l'éducation dans les pays en développement", response: "Les défis incluent le manque de ressources, l'accès limité aux écoles, la pénurie d'enseignants qualifiés, et les inégalités entre les zones urbaines et rurales." },
            { question: "livre pour apprendre le français", response: "Les meilleurs livres pour apprendre le français incluent 'Le Nouveau Taxi', 'Alter Ego', 'Grammaire progressive du français' et des livres de littérature simplifiée pour pratiquer la lecture." },

    { question: "Houssem Ben Ahmed", response: "Houssem Ben Ahmed est un étudiant en sciences informatiques, passionné par la programmation et la technologie. Il est également le créateur de l'IA HBA." },
    { question: "nationalité de Houssem", response: "Houssem Ben Ahmed est de nationalité tunisienne." },
    { question: "âge de Houssem", response: "Houssem a 19 ans." },
    { question: "intérêts de Houssem", response: "Houssem est passionné par l'informatique, la programmation, et le développement de projets en intelligence artificielle." },
    { question: "étudie Houssem", response: "Houssem est étudiant dans un programme en sciences informatiques dans ISI KEF." },
    { question: "projets de Houssem", response: "Houssem travaille sur divers projets, y compris la création de l'IA HBA, qui peut répondre aux questions et aider les utilisateurs dans divers domaines." },
    { question: "Pourquoi Houssem a-t-il créé HBA", response: "Houssem a créé HBA pour explorer le domaine de l'intelligence artificielle et pour fournir une assistance simple aux utilisateurs." },
    { question: "objectif de Houssem", response: "L'objectif de Houssem est de développer ses compétences en IA et en programmation tout en créant des projets utiles aux autres." },
    { question: "la date de création de HBA", response: "HBA a été créé le 28 octobre 2024 par Houssem Ben Ahmed." },
    { question: "Pourquoi Houssem a créé HBA", response: "Houssem a créé HBA pour explorer le domaine de l'intelligence artificielle et pour fournir une assistance simple aux utilisateurs." },


    { question: "science", response: "La science est l'étude systématique du monde naturel et physique par l'observation, l'expérimentation et la formulation de lois et de théories." },
    { question: "biologie", response: "La biologie est la science qui étudie les êtres vivants, leur structure, leur fonction, leur croissance et leur évolution." },
    { question: "chimie", response: "La chimie est la science qui étudie la composition, les propriétés et les transformations de la matière." },
    { question: "physique", response: "La physique est la science qui étudie les propriétés et le comportement de l'énergie et de la matière dans l'espace et le temps." },
    { question: "astronomie", response: "L'astronomie est l'étude des étoiles, des planètes et de l'univers dans son ensemble." },
    { question: "newton", response: "Isaac Newton était un physicien et mathématicien célèbre pour ses lois de la gravitation et de la mécanique classique." },
    { question: "évolution", response: "L'évolution est le processus par lequel les espèces changent au fil des générations par sélection naturelle et adaptation." },
    { question: "l'ADN", response: "L'ADN est une molécule qui contient les instructions génétiques nécessaires au développement et au fonctionnement des organismes vivants." },
    { question: "trou noir", response: "Un trou noir est une région de l'espace avec une gravité si intense que rien, même la lumière, ne peut s'en échapper." },
    { question: "Big Bang", response: "Le Big Bang est la théorie scientifique qui explique l'origine de l'univers comme une expansion rapide il y a environ 13,8 milliards d'années." },
    { question: "cellule", response: "La cellule est l'unité de base de la vie; tous les êtres vivants sont composés de cellules qui accomplissent des fonctions vitales." },
    { question: "changement climatique", response: "Le changement climatique désigne les modifications à long terme des températures et des régimes météorologiques de la Terre, principalement dues aux activités humaines." },
    { question: "photosynthèse", response: "La photosynthèse est le processus par lequel les plantes utilisent la lumière du soleil pour produire de l'énergie à partir du dioxyde de carbone et de l'eau." },
    { question: "énergie renouvelable", response: "L'énergie renouvelable provient de sources naturelles, comme le soleil, le vent et l'eau, qui peuvent être réapprovisionnées." },
    { question: "volcan", response: "Un volcan est une ouverture dans la croûte terrestre qui libère de la lave, des cendres et des gaz lorsque la pression interne est trop élevée." },
    { question: "Albert einstein", response: "Albert Einstein était un physicien connu pour sa théorie de la relativité, qui a changé notre compréhension de l'espace, du temps et de la gravité." },
    { question: "la théorie de la relativité", response: "La théorie de la relativité, proposée par Einstein, décrit comment la gravité affecte l'espace et le temps." },
    { question: "la génétique", response: "La génétique est l'étude de l'hérédité et de la variation des caractéristiques transmises des parents à leur progéniture." },
    { question: "la gravité", response: "La gravité est la force d'attraction exercée par les objets ayant une masse; elle est responsable de la chute des objets et de l'orbite des planètes." },

















];




// Fonction pour soumettre une question
function submitQuestion() {
    const userInput = document.getElementById("userInput").value.toLowerCase();
    const responsesDiv = document.getElementById("responses");

    // Effacer le champ de saisie
    document.getElementById("userInput").value = '';

    // Chercher une réponse dans la FAQ
    const match = faqList.find(faq => userInput.includes(faq.question));

    let responseMessage;
    if (match) {
        responseMessage = match.response;
    } else {
        responseMessage = "Désolé, je ne comprends pas la question,mais je le stoqué pour chercher des informations, Essayez de poser une autre question et merci!";
    }

    // Ajouter les messages à l'interface utilisateur
    responsesDiv.innerHTML += `<div><strong>Vous:</strong> ${userInput}</div>`;
    responsesDiv.innerHTML += `<div><strong>HBA-AI:</strong> ${responseMessage}</div>`;

    // Faire défiler la boîte de chat vers le bas
    const chatbox = document.getElementById("chatbox");
    chatbox.scrollTop = chatbox.scrollHeight;
}


document.getElementById('userInput').addEventListener('keydown', function(event) {
    if (event.key === 'Enter') {
        submitQuestion();
    }
});
